[project]
name = "crm"
authors = [
  { name = "Frappe Technologies Pvt. Ltd.", email = "shariq@frappe.io" }
]
description = "Kick-ass Open Source CRM"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
  # "frappe~=15.0.0"  # Installed and managed by bench.
  "twilio==8.5.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

# Tell Bench / Frappe Cloud which Frappe versions this app supports
[tool.bench.frappe-dependencies]
# Supports Frappe 15.x, 16.x, and 17.x
frappe = ">=15.0.0,<18.0.0"

[tool.bench.assets]
build_dir = "./frontend"
out_dir = "../crm/public/frontend"
index_html_path = "../crm/www/crm.html"

[tool.ruff]
line-length = 110
target-version = "py310"
exclude = [
  "**/doctype/*/boilerplate/*.py"  # boilerplate are template strings, not valid python
]

[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "UP",
  "B",
  "RUF",
]
ignore = [
  "B017",
  "B018",
  "B023",
  "B904",
  "E101",
  "E402",
  "E501",
  "E741",
  "F401",
  "F403",
  "F405",
  "F722",
  "W191",
  "RUF001",
  "UP030",
  "UP031",
  "UP032",
]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
